{% set version = "0.4-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rneos
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rneos_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rneos/rneos_{{ version }}.tar.gz
  sha256: 2ac777bb4cd2e93d35c02063932b8997ef50497d1484c1f188c44da6dab6f277

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcurl
    - r-xml
  run:
    - r-base
    - r-rcurl
    - r-xml

test:
  commands:
    - $R -e "library('rneos')"           # [not win]
    - "\"%R%\" -e \"library('rneos')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rneos
  license: GPL-2.0-or-later
  summary: Within this package the XML-RPC API to NEOS <https://neos-server.org/neos/> is implemented. This enables the user to pass optimization problems to NEOS and retrieve results within R.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - janjagusch


# Package: rneos
# Version: 0.4-0
# Date: 2020-04-22
# Title: XML-RPC Interface to NEOS
# Authors@R: c(person(given = "Bernhard", family = "Pfaff", email = "bernhard@pfaffikus.de", role = c("aut", "cre")), person(given = "Duncan Temple", family = "Lang", email = "<duncan@wald.ucdavis.edu", role = "ctb", comment = "included XMLRPC package, hosted at http://www.omegahat.net/XMLRPC/; BSD license."))
# Depends: R (>= 2.10.0), methods, RCurl, XML, stats
# LazyLoad: yes
# Description: Within this package the XML-RPC API to NEOS <https://neos-server.org/neos/> is implemented. This enables the user to pass optimization problems to NEOS and retrieve results within R.
# License: GPL (>= 2)
# Maintainer: Bernhard Pfaff <bernhard@pfaffikus.de>
# Repository: CRAN
# Repository/R-Forge/Project: rneos
# Repository/R-Forge/Revision: 267
# Repository/R-Forge/DateTimeStamp: 2020-04-22 12:56:33
# Date/Publication: 2020-04-23 07:40:02 UTC
# NeedsCompilation: no
# Packaged: 2020-04-22 13:10:08 UTC; rforge
# Author: Bernhard Pfaff [aut, cre], Duncan Temple Lang [ctb] (included XMLRPC package, hosted at http://www.omegahat.net/XMLRPC/; BSD license.)
